### ISSUE TITLE
Cut line

### ISSUE THREAD

**Issue by ipod86** [ioBroker/ioBroker.echarts#9] opened 2020-11-28 07:36 UTC
In the case of an individually entered range of values, the line is not cut off when exiting the chart.  To clarify, a comparison to flot.

![Screenshot_20201128-085514_Fully Kiosk Browser](https://user-images.githubusercontent.com/66136363/100496825-97956c00-3157-11eb-8449-f333e750084e.jpg)

**Comment by GermanBluefox** [comment] 2020-11-28 13:51
Unfortunately I cannot reproduce it...
![image](https://user-images.githubusercontent.com/4582016/100517130-dee82080-3188-11eb-875d-37cfb0ea3bb4.png)

and here with only upper limit:
![image](https://user-images.githubusercontent.com/4582016/100517145-0212d000-3189-11eb-9930-da99e77cc740.png)

**Comment by ipod86** [comment] 2020-11-28 13:55
Is there something I can provide to understand the cause?

**Comment by GermanBluefox** [comment] 2020-11-28 14:07
The preset object: 
![image](https://user-images.githubusercontent.com/4582016/100517522-515a0000-318b-11eb-8bae-69616ffb3284.png)

I will replace the IDs and will try to reproduce your case

**Comment by ipod86** [comment] 2020-11-29 17:17
![echart](https://user-images.githubusercontent.com/66136363/100548779-fb5e8880-326e-11eb-9d3c-fed3aead5167.JPG)

`
{
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1606462596840,
  "common": {
    "name": "Wohnzimmer copy"
  },
  "native": {
    "url": "",
    "data": {
      "lines": [
        {
          "name": "Luftfeuchte",
          "id": "alias.0.og.Thermostat_Wohnbereich.HUMIDITY",
          "instance": "system.adapter.sql.0",
          "thickness": "3",
          "chartType": "line",
          "aggregate": "minmax",
          "isBoolean": false,
          "symbolSize": 3,
          "validTime": "35",
          "unit": "%",
          "fill": 0,
          "color": "#4285f4",
          "lineStyle": "solid",
          "commonYAxis": "",
          "yaxe": "right",
          "min": "50",
          "max": "80",
          "points": false,
          "yticks": ""
        }
      ],
      "marks": [],
      "timeType": "relative",
      "relativeEnd": "now",
      "range": "1440",
      "aggregateType": "count",
      "aggregateSpan": "100",
      "legend": "",
      "hoverDetail": true,
      "zoom": false,
      "animation": 0,
      "live": "300",
      "ticks": "",
      "width": "100%",
      "height": "100%",
      "noBorder": "noborder",
      "window_bg": "rgba(0, 0, 0, 0)",
      "bg_custom": "rgba(0, 0, 0, 0)",
      "x_labels_color": "#121213",
      "y_labels_color": "#0c0c0c",
      "border_color": "",
      "grid_color": "rgba(255, 255, 255, 0.11)",
      "grid_hideX": false,
      "grid_hideY": false,
      "border_width": "",
      "barColor": "",
      "barLabels": "topover",
      "barWidth": "",
      "barFontSize": "",
      "barFontColor": "",
      "title": "",
      "titlePos": "",
      "titleColor": "#4024cb",
      "titleSize": "",
      "legColumns": "",
      "legBgOpacity": "",
      "legBg": "rgba(255, 255, 255, 0.11)",
      "timeFormat": "dd HH:mm",
      "export": false,
      "useComma": false,
      "hoverNoNulls": true,
      "theme": "default",
      "legColor": "#ffffff",
      "x_ticks_color": "rgba(255, 255, 255, 0.11)",
      "y_ticks_color": "rgba(255, 255, 255, 0.11)",
      "timeFormatCustom": true,
      "noBackground": true
    }
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "_id": "echarts.0.Heizung.Wohnzimmer_copy",
  "type": "chart"
}
`

**Comment by GermanBluefox** [comment] 2020-11-29 19:38
Thank you. Fixed in 0.4.2

**Closed** 2020-12-11 11:07 UTC
Labels: fixed
